name: Go

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: kerberos/base:91ab4d4

    strategy:
      matrix:
        go-version: [1.17, 1.18]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.1.0
    - name: Install dependencies
      run: apt update -y && apt install -y --no-install-recommends git build-essential cmake pkg-config unzip libgtk2.0-dev curl ca-certificates libcurl4-openssl-dev libssl-dev libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libpng-dev libtiff-dev libdc1394-22-dev libjpeg62-turbo-dev
    - name: Get dependencies
      run: cd machinery && go mod download
    - name: Build
      run: cd machinery && go build -v ./...
    - name: Vet
      run: cd machinery && go vet -v ./...
    - name: Test
      run: cd machinery && go test -v ./...
