name: Go

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: cd machinery && go mod download

    - name: Build
      run: cd machinery && go build -v ./...

    - name: Vet
      run: cd machinery && go vet -v ./...

    - name: Test
      run: cd machinery && go test -v ./...
